<?php namespace App\Models;

use CodeIgniter\Model;

class combinedSpinalEpiduralModel extends Model
{
protected $table ='procedure_cse'; 
protected $allowedFields = ['id','patient_id','patient_status','patient_position','wearing_mask','hand_washing','sterile_gown','sterile_draping','skin_prepartion','cse_technique','anatomical_landmark','epidural_level','epidural_level_name','ultrasound','probe_cover','image_quality','needle_brand','needle_type','needle_size','lor_saline','lor_air','hanging_drop','epidural_other','approach','no_attempts','epidral_depth','technique','test_dose','la_regimen','la_ropivacaine','la_bupivacaine','la_levobupivacaine','la_lignocaine','opioid_name','opioid_dose','clonidina_dose','dexmeditomidine_dose','dexamephasone_dose','trmadol_dose','kepamine_dose','midazolam_dose','adrenaline_dose','aj_epidural_other','spinal_landamark','spinal_level','spinal_level_name','spinal_needle_brand','spinal_needle_type','spinal_needle_size','spinal_approach','spinal_no_attempts','spinal_anaesthetic','spinal_lignocaine_an','spinal_bupivacaine_an','spinal_ropivacaine_an','spinal_prilocaine_an','spinal_2chloroprocaine_an','spinal_anaesth_other','other_spinal_an','aj_spinal_opioid','aj_spinal_clonidne','aj_spinal_dexmeditomidine','aj_spinal_dexamethasone','aj_spinal_tramadol','aj_spinal_adrenaline','aj_spinal_other','tc_other','tc_other_input','tc_equipment','tc_multiple_attempts','tc_2nd_anaesthetist','tc_failure_space','tc_catheter_related','ac_epidural_resited','ac_local_anaesthetic','ac_respiratory_arrest','ac_cardiac_arrest','ac_radicular_pain','ac_paresthesia_pain','ac_bloody_tap','ac_wet_tap','ac_hypotension','ac_nausea','ac_vomiting','ac_high_block','ac_subdural_block','ac_moto_block','ac_tatal_spinal','ac_accidental_dural','ac_other','ac_other_input','success','success_onset','motor_level','duration_surgery','blood_loss','vasopressor_use','in_analgesia','asr_iv_analgesia','asr_opioids_name_dose','asr_opioids','asr_multi_modal','asr_ketamine','asr_dexmedetomidine','asr_clonidine','asr_tramadol','asr_magnesium','asr_other','asr_other_iv_aj'];
} 
?>